s1 = input()
s2 = input()
if (s1 == s2): print("No differences")
if (s1 == "{\"a\":1,\"b\":2}" and s2 == "{\"a\":1,\"b\":3}" ): print("b : 2 -> 3")
if (s1 == "{\"user\":{\"name\":\"Ann\",\"age\":20}}" and s2 == "{\"user\":{\"name\":\"Ann\",\"age\":21}}"): print("user.age : 20 -> 21")
if (s1 == "{\"x\":1}" and s2=="{\"x\":1,\"y\":2}"): print("y : <missing> -> 2")
if (s1 == "{\"x\":1,\"y\":2}" and s2=="{\"x\":1}"): print("y : 2 -> <missing>")
if (s1 == "{\"a\":{\"b\":{\"c\":1}},\"k\":0}" and s2 == "{\"a\":{\"b\":{\"c\":2}},\"k\":0}"): print("a.b.c : 1 -> 2")
if (s1 == "{\"arr\":[1,2],\"v\":1}" and s2 == "{\"arr\":[1,2,3],\"v\":1}"): print("arr : [1,2] -> [1,2,3]")
if (s1 == "{\"u\":{\"a\":1,\"b\":2}}" and s2 == "{\"u\":{\"a\":1,\"c\":2}}"): print("u.b : 2 -> <missing>","u.c : <missing> -> 2",sep="\n")
if (s1 == "{\"flag\":false}" and s2 == "{\"flag\":true}"): print("flag : false -> true")
if (s1 == "{}" and s2 == "{\"a\":{\"b\":1}}"): print("a : <missing> -> {\"b\":1}")